=== molbazsa/KFIXBJ_XMLGyak/XMLTaskKFIXBJ/XMLSchemaKFIXBJ.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="vonatjegyek">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="allomas" type="allomasTipus" maxOccurs="unbounded" />
                <xs:element name="tavolsaga" type="tavolsagaTipus" maxOccurs="unbounded" />
                <xs:element name="vonat" type="vonatTipus" maxOccurs="unbounded" />
                <xs:element name="kocsi" type="kocsiTipus" maxOccurs="unbounded" />
                <xs:element name="erinti" type="erintiTipus" maxOccurs="unbounded" />
                <xs:element name="utas" type="utasTipus" maxOccurs="unbounded" />
                <xs:element name="jegy" type="jegyTipus" maxOccurs="unbounded" />
            </xs:sequence>
        </xs:complexType>

        <xs:key name="allomas">
            <xs:selector xpath="allomas" />
            <xs:field xpath="@aid" />
        </xs:key>

        <xs:keyref name="tavolsagaAllomas1" refer="allomas">
            <xs:selector xpath="tavolsaga" />
            <xs:field xpath="@aid1" />
        </xs:keyref>
        <xs:keyref name="tavolsagaAllomas2" refer="allomas">
            <xs:selector xpath="tavolsaga" />
            <xs:field xpath="@aid2" />
        </xs:keyref>

        <xs:key name="vonat">
            <xs:selector xpath="vonat" />
            <xs:field xpath="@vid" />
        </xs:key>

        <xs:key name="kocsi">
            <xs:selector xpath="kocsi" />
            <xs:field xpath="@kid" />
        </xs:key>
        <xs:keyref name="kocsiVonat" refer="vonat">
            <xs:selector xpath="kocsi" />
            <xs:field xpath="@vid" />
        </xs:keyref>

        <xs:keyref name="erintiVonat" refer="vonat">
            <xs:selector xpath="erinti" />
            <xs:field xpath="@vid" />
        </xs:keyref>
        <xs:keyref name="erintiAllomas" refer="allomas">
            <xs:selector xpath="erinti" />
            <xs:field xpath="@aid" />
        </xs:keyref>

        <xs:key name="utas">
            <xs:selector xpath="utas" />
            <xs:field xpath="@uid" />
        </xs:key>

        <xs:keyref name="jegyUtas" refer="utas">
            <xs:selector xpath="jegy" />
            <xs:field xpath="@uid" />
        </xs:keyref>
        <xs:keyref name="jegyVonat" refer="vonat">
            <xs:selector xpath="jegy" />
            <xs:field xpath="@vid" />
        </xs:keyref>
        <xs:keyref name="jegyAllomas1" refer="allomas">
            <xs:selector xpath="jegy" />
            <xs:field xpath="@aid1" />
        </xs:keyref>
        <xs:keyref name="jegyAllomas2" refer="allomas">
            <xs:selector xpath="jegy" />
            <xs:field xpath="@aid2" />
        </xs:keyref>

        <xs:keyref name="helyjegyKocsi" refer="kocsi">
            <xs:selector xpath="jegy/helyjegy" />
            <xs:field xpath="@kid" />
        </xs:keyref>
    </xs:element>

    <xs:complexType name="allomasTipus">
        <xs:sequence>
            <xs:element name="iranyitoszam" type="xs:integer" />
            <xs:element name="utca" type="xs:string" />
            <xs:element name="hazszam" type="xs:string" />
            <xs:element name="nev" type="xs:string" />
        </xs:sequence>

        <xs:attribute name="aid" type="xs:ID" use="required" />
    </xs:complexType>

    <xs:complexType name="tavolsagaTipus">
        <xs:sequence>
            <xs:element name="tavolsag" type="xs:integer" />
        </xs:sequence>

        <xs:attribute name="aid1" type="xs:IDREF" use="required" />
        <xs:attribute name="aid2" type="xs:IDREF" use="required" />
    </xs:complexType>

    <xs:complexType name="vonatTipus">
        <xs:sequence>
            <xs:element name="vonalszam" type="xs:integer" />
            <xs:element name="indulas" type="xs:dateTime" />
            <xs:element name="erkezes" type="xs:dateTime" />
            <xs:element name="tavolsag" type="xs:integer" />
            <xs:element name="helyjegy-koteles" type="xs:boolean" />
        </xs:sequence>

        <xs:attribute name="vid" type="xs:ID" use="required" />
    </xs:complexType>

    <xs:complexType name="kocsiTipus">
        <xs:sequence>
            <xs:element name="kocsiosztaly" type="xs:integer" />
        </xs:sequence>

        <xs:attribute name="vid" type="xs:IDREF" use="required" />
        <xs:attribute name="kid" type="xs:ID" use="required" />
    </xs:complexType>

    <xs:complexType name="erintiTipus">
        <xs:sequence>
            <xs:element name="vegallomas" type="xs:boolean" />
        </xs:sequence>

        <xs:attribute name="vid" type="xs:IDREF" use="required" />
        <xs:attribute name="aid" type="xs:IDREF" use="required" />
    </xs:complexType>

    <xs:complexType name="utasTipus">
        <xs:sequence>
            <xs:element name="nev" type="xs:string" />
            <xs:element name="email" type="xs:string" maxOccurs="unbounded" />
        </xs:sequence>

        <xs:attribute name="uid" type="xs:ID" use="required" />
    </xs:complexType>

    <xs:complexType name="jegyTipus">
        <xs:sequence>
            <xs:element name="ar" type="xs:integer" />
            <xs:element name="helyjegy" type="helyjegyTipus" minOccurs="0" />
        </xs:sequence>

        <xs:attribute name="jid" type="xs:ID" use="required" />
        <xs:attribute name="uid" type="xs:IDREF" use="required" />
        <xs:attribute name="vid" type="xs:IDREF" use="required" />
        <xs:attribute name="aid1" type="xs:IDREF" use="required" />
        <xs:attribute name="aid2" type="xs:IDREF" use="required" />
    </xs:complexType>

    <xs:complexType name="helyjegyTipus">
        <xs:sequence>
            <xs:element name="ulesszam" type="xs:integer" />
            <xs:element name="ar" type="xs:integer" />
        </xs:sequence>

        <xs:attribute name="kid" type="xs:IDREF" use="required" />
        <xs:attribute name="hid" type="xs:ID" use="required" />
    </xs:complexType>
</xs:schema>

=== molbazsa/KFIXBJ_XMLGyak/XMLTaskKFIXBJ/XMLKFIXBJ.xml
<?xml version="1.0" encoding="UTF-8"?>
<vonatjegyek xmlns:xs="http://www.w3.org/2001/XMLSchema-instance" xs:noNamespaceSchemaLocation="XMLSchemaKFIXBJ.xsd">
    <!-- Állomások -->
    <allomas aid="a1">
        <iranyitoszam>1087</iranyitoszam>
        <utca>Kerepesi út</utca>
        <hazszam>2-4.</hazszam>
        <nev>Budapest-Keleti</nev>
    </allomas>
    <allomas aid="a2">
        <iranyitoszam>3530</iranyitoszam>
        <utca>Kandó Kálmán tér</utca>
        <hazszam>1-3.</hazszam>
        <nev>Miskolc-Tiszai</nev>
    </allomas>
    <allomas aid="a3">
        <iranyitoszam>6700</iranyitoszam>
        <utca>Tisza Lajos körút</utca>
        <hazszam>28-30.</hazszam>
        <nev>Szeged</nev>
    </allomas>
    <allomas aid="a4">
        <iranyitoszam>7623</iranyitoszam>
        <utca>Indóház tér</utca>
        <hazszam>1.</hazszam>
        <nev>Pécs</nev>
    </allomas>

    <!-- Állomások távolsága -->
    <tavolsaga aid1="a1" aid2="a2">
        <tavolsag>147</tavolsag>
    </tavolsaga>
    <tavolsaga aid1="a1" aid2="a3">
        <tavolsag>162</tavolsag>
    </tavolsaga>
    <tavolsaga aid1="a1" aid2="a4">
        <tavolsag>170</tavolsag>
    </tavolsaga>

    <!-- Vonatok -->
    <vonat vid="v1">
        <vonalszam>1</vonalszam>
        <indulas>2022-11-29T08:00:00</indulas>
        <erkezes>2022-11-29T10:30:00</erkezes>
        <tavolsag>200</tavolsag>
        <helyjegy-koteles>false</helyjegy-koteles>
    </vonat>
    <vonat vid="v2">
        <vonalszam>2</vonalszam>
        <indulas>2022-11-29T09:00:00</indulas>
        <erkezes>2022-11-29T11:00:00</erkezes>
        <tavolsag>250</tavolsag>
        <helyjegy-koteles>true</helyjegy-koteles>
    </vonat>
    <vonat vid="v3">
        <vonalszam>3</vonalszam>
        <indulas>2022-11-29T11:00:00</indulas>
        <erkezes>2022-11-29T14:30:00</erkezes>
        <tavolsag>300</tavolsag>
        <helyjegy-koteles>true</helyjegy-koteles>
    </vonat>

    <!-- Kocsik -->
    <kocsi vid="v1" kid="k12">
        <kocsiosztaly>1</kocsiosztaly>
    </kocsi>
    <kocsi vid="v1" kid="k13">
        <kocsiosztaly>2</kocsiosztaly>
    </kocsi>
    <kocsi vid="v1" kid="k14">
        <kocsiosztaly>2</kocsiosztaly>
    </kocsi>
    <kocsi vid="v2" kid="k44">
        <kocsiosztaly>1</kocsiosztaly>
    </kocsi>
    <kocsi vid="v2" kid="k45">
        <kocsiosztaly>1</kocsiosztaly>
    </kocsi>
    <kocsi vid="v2" kid="k46">
        <kocsiosztaly>2</kocsiosztaly>
    </kocsi>
    <kocsi vid="v3" kid="k76">
        <kocsiosztaly>1</kocsiosztaly>
    </kocsi>
    <kocsi vid="v3" kid="k77">
        <kocsiosztaly>1</kocsiosztaly>
    </kocsi>
    <kocsi vid="v3" kid="k78">
        <kocsiosztaly>2</kocsiosztaly>
    </kocsi>

    <!-- Vonatok állomásai -->
    <erinti vid="v1" aid="a1">
        <vegallomas>true</vegallomas>
    </erinti>
    <erinti vid="v1" aid="a2">
        <vegallomas>false</vegallomas>
    </erinti>
    <erinti vid="v1" aid="a3">
        <vegallomas>true</vegallomas>
    </erinti>
    <erinti vid="v2" aid="a1">
        <vegallomas>true</vegallomas>
    </erinti>
    <erinti vid="v2" aid="a2">
        <vegallomas>false</vegallomas>
    </erinti>
    <erinti vid="v2" aid="a3">
        <vegallomas>false</vegallomas>
    </erinti>
    <erinti vid="v2" aid="a4">
        <vegallomas>true</vegallomas>
    </erinti>

    <!-- Utasok -->
    <utas uid="u1">
        <nev>Szőke Alex</nev>
        <email>szalex@email.com</email>
        <email>szoke.alex@email.com</email>
    </utas>
    <utas uid="u2">
        <nev>Farkas Blanka</nev>
        <email>fblanka@email.com</email>
    </utas>
    <utas uid="u3">
        <nev>Boros Máté</nev>
        <email>bmate@email.com</email>
    </utas>
    <utas uid="u4">
        <nev>Pap Hanna</nev>
        <email>phanna@email.com</email>
        <email>pap.hanna@email.com</email>
    </utas>

    <!-- Jegyek -->
    <jegy jid="j1" uid="u1" vid="v1" aid1="a1" aid2="a2">
        <ar>700</ar>
    </jegy>
    <jegy jid="j2" uid="u2" vid="v3" aid1="a2" aid2="a4">
        <ar>650</ar>
        <helyjegy hid="h1" kid="k76">
            <ulesszam>12</ulesszam>
            <ar>150</ar>
        </helyjegy>
    </jegy>
    <jegy jid="j3" uid="u4" vid="v2" aid1="a3" aid2="a4">
        <ar>700</ar>
    </jegy>
</vonatjegyek>

=== molbazsa/KFIXBJ_XMLGyak/XMLTaskKFIXBJ/XMLKFIXBJ.mod.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<vonatjegyek xmlns:xs="http://www.w3.org/2001/XMLSchema-instance" xs:noNamespaceSchemaLocation="XMLSchemaKFIXBJ.xsd">
    <!-- Állomások -->
    <allomas aid="a1">
        <iranyitoszam>1087</iranyitoszam>
        <utca>Kerepesi út</utca>
        <hazszam>2-4.</hazszam>
        <nev>Budapest-Keleti</nev>
    </allomas>
    <allomas aid="a2">
        <iranyitoszam>3530</iranyitoszam>
        <utca>Kandó Kálmán tér</utca>
        <hazszam>1-3.</hazszam>
        <nev>Miskolc-Tiszai</nev>
    </allomas>
    <allomas aid="a3">
        <iranyitoszam>6700</iranyitoszam>
        <utca>Tisza Lajos körút</utca>
        <hazszam>28-30.</hazszam>
        <nev>Szeged</nev>
    </allomas>
    <allomas aid="a4">
        <iranyitoszam>7623</iranyitoszam>
        <utca>Indóház tér</utca>
        <hazszam>1.</hazszam>
        <nev>Pécs</nev>
    </allomas>
    <!-- Állomások távolsága -->
    <tavolsaga aid1="a1" aid2="a2">
        <tavolsag>294</tavolsag>
    </tavolsaga>
    <tavolsaga aid1="a1" aid2="a3">
        <tavolsag>324</tavolsag>
    </tavolsaga>
    <tavolsaga aid1="a1" aid2="a4">
        <tavolsag>340</tavolsag>
    </tavolsaga>
    <!-- Vonatok -->
    <vonat vid="v1">
        <vonalszam>1</vonalszam>
        <indulas>2022-11-29T08:00:00</indulas>
        <erkezes>2022-11-29T10:30:00</erkezes>
        <tavolsag>200</tavolsag>
        <helyjegy-koteles>false</helyjegy-koteles>
    </vonat>
    <vonat vid="v2">
        <vonalszam>2</vonalszam>
        <indulas>2022-11-29T09:00:00</indulas>
        <erkezes>2022-11-29T11:00:00</erkezes>
        <tavolsag>250</tavolsag>
        <helyjegy-koteles>true</helyjegy-koteles>
    </vonat>
    <vonat vid="v3">
        <vonalszam>3</vonalszam>
        <indulas>2022-11-29T11:00:00</indulas>
        <erkezes>2022-11-29T14:30:00</erkezes>
        <tavolsag>300</tavolsag>
        <helyjegy-koteles>true</helyjegy-koteles>
    </vonat>
    <!-- Kocsik -->
    <kocsi kid="k79" vid="v3">
        <kocsiosztaly>1</kocsiosztaly>
    </kocsi>
    <kocsi kid="k12" vid="v1">
        <kocsiosztaly>1</kocsiosztaly>
    </kocsi>
    <kocsi kid="k13" vid="v1">
        <kocsiosztaly>2</kocsiosztaly>
    </kocsi>
    <kocsi kid="k14" vid="v1">
        <kocsiosztaly>2</kocsiosztaly>
    </kocsi>
    <kocsi kid="k44" vid="v2">
        <kocsiosztaly>1</kocsiosztaly>
    </kocsi>
    <kocsi kid="k45" vid="v2">
        <kocsiosztaly>1</kocsiosztaly>
    </kocsi>
    <kocsi kid="k46" vid="v2">
        <kocsiosztaly>2</kocsiosztaly>
    </kocsi>
    <kocsi kid="k76" vid="v3">
        <kocsiosztaly>1</kocsiosztaly>
    </kocsi>
    <kocsi kid="k77" vid="v3">
        <kocsiosztaly>1</kocsiosztaly>
    </kocsi>
    <kocsi kid="k78" vid="v3">
        <kocsiosztaly>2</kocsiosztaly>
    </kocsi>
    <!-- Vonatok állomásai -->
    <erinti aid="a4" vid="v3">
        <vegallomas>true</vegallomas>
    </erinti>
    <erinti aid="a1" vid="v1">
        <vegallomas>true</vegallomas>
    </erinti>
    <erinti aid="a2" vid="v1">
        <vegallomas>false</vegallomas>
    </erinti>
    <erinti aid="a3" vid="v1">
        <vegallomas>true</vegallomas>
    </erinti>
    <erinti aid="a1" vid="v2">
        <vegallomas>true</vegallomas>
    </erinti>
    <erinti aid="a2" vid="v2">
        <vegallomas>false</vegallomas>
    </erinti>
    <erinti aid="a3" vid="v2">
        <vegallomas>false</vegallomas>
    </erinti>
    <erinti aid="a4" vid="v2">
        <vegallomas>true</vegallomas>
    </erinti>
    <!-- Utasok -->
    <utas uid="u1">
        <nev>Szőke Alex</nev>
        <email>szalex@email.com</email>
        <email>szoke.alex@email.com</email>
    </utas>
    <utas uid="u2">
        <nev>Farkas Blanka</nev>
        <email>fblanka@email.com</email>
    </utas>
    <utas uid="u3">
        <nev>Boros Máté</nev>
        <email>boros.mate@email.com</email>
        <email>bmate@email.com</email>
    </utas>
    <utas uid="u4">
        <nev>Pap Hanna</nev>
        <email>phanna@email.com</email>
        <email>pap.hanna@email.com</email>
    </utas>
    <!-- Jegyek -->
    <jegy aid1="a1" aid2="a2" jid="j1" uid="u1" vid="v1">
        <ar>800</ar>
    </jegy>
    <jegy aid1="a2" aid2="a4" jid="j2" uid="u2" vid="v3">
        <ar>750</ar>
        <helyjegy hid="h1" kid="k76">
            <ulesszam>12</ulesszam>
            <ar>150</ar>
        </helyjegy>
    </jegy>
    <jegy aid1="a3" aid2="a4" jid="j3" uid="u4" vid="v2">
        <ar>800</ar>
    </jegy>
</vonatjegyek>
