=== molbazsa/KFIXBJ_XMLGyak/KFIXBJ_0928/MB_ertodtd.dtd
<!ELEMENT MBmodell (A*, B*, C*, AB*)>

<!ELEMENT A (b, c)>
<!ATTLIST A a ID #REQUIRED>

<!ELEMENT B (b)>
<!ATTLIST B
  a ID #REQUIRED
  c IDREF #REQUIRED
>

<!ELEMENT b (x, y)>
<!ELEMENT x (#PCDATA)>
<!ELEMENT y (#PCDATA)>

<!ELEMENT c (d, e)>
<!ELEMENT d (#PCDATA)>
<!ELEMENT e (#PCDATA)>

<!ELEMENT C (C-b)>
<!ATTLIST C a ID #REQUIRED>
<!ELEMENT C-b (#PCDATA)>

<!ELEMENT AB (AB-c)>
<!ATTLIST AB
  a IDREF #REQUIRED
  b IDREF #REQUIRED
>
<!ELEMENT AB-c (#PCDATA)>

=== molbazsa/KFIXBJ_XMLGyak/KFIXBJ_0928/MB_dtdtoxml.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE MBmodell SYSTEM "./MB_ertodtd.dtd">

<MBmodell>

  <A a="A01">
    <b>
      <x>x1</x>
      <y>y1</y>
    </b>
    <c>
      <d>d1</d>
      <e>e1</e>
    </c>
  </A>

  <A a="A02">
    <b>
      <x>x2</x>
      <y>y2</y>
    </b>
    <c>
      <d>d2</d>
      <e>e2</e>
    </c>
  </A>
  
  <B a="B01" c="C01">
    <b>
      <x>x1</x>
      <y>y1</y>
    </b>
  </B>

  <B a="B02" c="C01">
    <b>
      <x>x2</x>
      <y>y2</y>
    </b>
  </B>

  <C a="C01">
    <C-b>b1</C-b>
  </C>

  <AB a="A01" b="B01">
    <AB-c>c1</AB-c>
  </AB>

  <AB a="A01" b="B02">
    <AB-c>c2</AB-c>
  </AB>

  <AB a="A02" b="B01">
    <AB-c>c3</AB-c>
  </AB>

</MBmodell>
