=== molbazsa/KFIXBJ_XMLGyak/KFIXBJ_0928/MB_kurzusfelvetel.dtd
<!ELEMENT MB_kurzusfelvetel (kurzus*)>

<!ELEMENT kurzus (targy, idopont+, (oktato|oraado)?)>
<!ATTLIST kurzus jovahagyas (igen|nem) "nem">

<!ELEMENT idopont (nap, tol, ig)>
<!ELEMENT nap (#PCDATA)>
<!ELEMENT tol (#PCDATA)>
<!ELEMENT ig (#PCDATA)>

<!ELEMENT targy (#PCDATA)>
<!ELEMENT oktato (#PCDATA)>
<!ELEMENT oraado (#PCDATA)>

=== molbazsa/KFIXBJ_XMLGyak/KFIXBJ_0928/MB_kurzusfelvetel.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE MB_kurzusfelvetel SYSTEM "./MB_kurzusfelvetel.dtd">

<MB_kurzusfelvetel>

  <kurzus>
    <targy>Mesterséges intelligencia</targy>
    <idopont>
      <nap>kedd</nap>
      <tol>09:00</tol>
      <ig>12:00</ig>
    </idopont>
    <idopont>
      <nap>szerda</nap>
      <tol>14:00</tol>
      <ig>15:00</ig>
    </idopont>
    <oraado>Kunné Dr. Tamás Judit</oraado>
  </kurzus>

  <kurzus jovahagyas="igen">
    <targy>Adatkezelés XML-ben</targy>
    <idopont>
      <nap>kedd</nap>
      <tol>12:00</tol>
      <ig>14:00</ig>
    </idopont>
    <idopont>
      <nap>szerda</nap>
      <tol>12:00</tol>
      <ig>14:00</ig>
    </idopont>
    <oktato>Dr. Bednarik László</oktato>
  </kurzus>

</MB_kurzusfelvetel>
