=== molbazsa/KFIXBJ_XMLGyak/KFIXBJ_0928/MB_orarend.dtd
<!ELEMENT MB_orarend (ora*)>

<!ELEMENT ora (targy, idopont, helyszin, oktato, szak)>
<!ATTLIST ora 
  id ID #REQUIRED
  tipus (eloadas|gyakorlat) #REQUIRED
>

<!ELEMENT idopont (nap, tol, ig)>
<!ELEMENT nap (#PCDATA)>
<!ELEMENT tol (#PCDATA)>
<!ELEMENT ig (#PCDATA)>

<!ELEMENT targy (#PCDATA)>
<!ELEMENT helyszin (#PCDATA)>
<!ELEMENT oktato (#PCDATA)>
<!ELEMENT szak (#PCDATA)>

=== molbazsa/KFIXBJ_XMLGyak/KFIXBJ_0928/MB_orarend.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE MB_orarend SYSTEM "./MB_orarend.dtd">

<MB_orarend>

  <ora id="ora_01" tipus="eloadas">
    <targy>Mesterséges intelligencia</targy>
    <idopont>
      <nap>kedd</nap>
      <tol>09:00</tol>
      <ig>12:00</ig>
    </idopont>
    <helyszin>I. előadó</helyszin>
    <oktato>Kunné Dr. Tamás Judit</oktato>
    <szak>programtervező informatikus</szak>
  </ora>

  <ora id="ora_02" tipus="eloadas">
    <targy>Adatkezelés XML-ben</targy>
    <idopont>
      <nap>kedd</nap>
      <tol>12:00</tol>
      <ig>14:00</ig>
    </idopont>
    <helyszin>XXXII. előadó</helyszin>
    <oktato>Dr. Bednarik László</oktato>
    <szak>programtervező informatikus</szak>
  </ora>

  <ora id="ora_03" tipus="eloadas">
    <targy>Algoritmusok és vizsgálatuk</targy>
    <idopont>
      <nap>kedd</nap>
      <tol>14:00</tol>
      <ig>18:00</ig>
    </idopont>
    <helyszin>X. előadó</helyszin>
    <oktato>Dr. Házy Attila</oktato>
    <szak>programtervező informatikus</szak>
  </ora>

  <ora id="ora_04" tipus="gyakorlat">
    <targy>Adatkezelés XML-ben</targy>
    <idopont>
      <nap>szerda</nap>
      <tol>12:00</tol>
      <ig>14:00</ig>
    </idopont>
    <helyszin>In/101</helyszin>
    <oktato>Dr. Bednarik László</oktato>
    <szak>programtervező informatikus</szak>
  </ora>

  <ora id="ora_05" tipus="gyakorlat">
    <targy>Mesterséges intelligencia</targy>
    <idopont>
      <nap>szerda</nap>
      <tol>14:00</tol>
      <ig>15:00</ig>
    </idopont>
    <helyszin>In/15</helyszin>
    <oktato>Fazekas Levente</oktato>
    <szak>programtervező informatikus</szak>
  </ora>

  <ora id="ora_06" tipus="eloadas">
    <targy>Vállalati információs rendszerek</targy>
    <idopont>
      <nap>szerda</nap>
      <tol>16:00</tol>
      <ig>20:00</ig>
    </idopont>
    <helyszin>In/103</helyszin>
    <oktato>Dr. Sasvári Péter</oktato>
    <szak>programtervező informatikus</szak>
  </ora>

  <ora id="ora_07" tipus="gyakorlat">
    <targy>Játék prototípusok</targy>
    <idopont>
      <nap>csütörtök</nap>
      <tol>14:00</tol>
      <ig>18:00</ig>
    </idopont>
    <helyszin>In/15</helyszin>
    <oktato>Szabó Martin</oktato>
    <szak>programtervező informatikus</szak>
  </ora>

</MB_orarend>
